DefaultContentLanguage = "en"
copyright = "CC Cristina Wood"

[languages]
  [languages.en]
    title = "Flows of Industry"
    weight = 1
    [languages.en.params]
      linkedin = "english-link"
  [languages.fr]
    copyright = "CC Cristina Wood"
    title = "Un fleuve d'industrie"
    weight = 2
    [languages.fr.params]
      linkedin = "lien-francais"
      [languages.fr.params.navigation]
        help = "Aide"

[params]
  [params.navigation]
    help = "Help"